### ISSUE TITLE
Validate GraphQL queries/mutation names do not collide

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#1066]
### Current Behavior
Validate that GraphQL query and mutation names do not collide. This check occurs prior to GraphQLSchemaBuilder execution which creates the GraphQL schema utilizing permissions metadata from the authorization resolver. The collision check runs regardless of any permissions set in the runtime config and may be unnecessarily validating against a collision that will not be a problem due to the particular query or mutation not being add to generated GraphQL schema.

### Suggested Behavior
Validate that GraphQL query and mutation names do not collide based on permissions metadata because certain query and mutation fields may not be created/included in the GraphQL schema if zero permissions allow the particular query/mutation operation. 

_Originally posted by @severussundar in https://github.com/Azure/data-api-builder/pull/1060#discussion_r1059267412_

**Comment by seantleonard** [comment]
Determine if this results in helpful error messages as-is or if there is a bug.

**Comment by seantleonard** [comment]
I am hesitant to implement this because by doing so we are effectively saying:
- Authorization rules configured in one entity affect the naming configuration in a different entity. This adds logical complexity to a configuration that should remain easy to modify and understand.
- An authorization rule change that ultimately prevents the engine from starting up due to this validation failing would require cascading changes to other entities which a developer may not desire to make in a production workload. Downstream apps and dependencies may not be expecting GraphQL schema changes caused by authorization rule changes. 

Example config that fails today but would pass the validation suggested in this issue:

```json
"ProductCatalogue": {
  "source": "productcatalogue",
  "permissions": [
    {
      "role": "authenticated",
      "actions": [
        "create"
      ]
    }
  ],
  "graphql": {
    "type": {
      "singular": "Product",
      "plural": "Products"
    }
  }
},
"Product": {
  "source": "products",
  "permissions": [
    {
      "role": "authenticated",
      "actions": [
        "read",
        "delete",
        "update"
      ]
    }
  ]
}
```

That fails today is because DAB checks query and mutation names without considering authorization rules/permissions.

If this GraphQL query/mutation name duplication check validation is skipped here: https://github.com/Azure/data-api-builder/blob/dacf3bccbe0a36da51776bf4afd1b4a0d4348ff4/src/Core/Configurations/RuntimeConfigValidator.cs#L329-L349

Then more issues will arise as the remainder of the GraphQL schema is generated. The operation responsible for generating the GraphQL object type definitions, their input types, and their fields expects that at least one role is defined for the entity. (see: https://github.com/Azure/data-api-builder/blob/dacf3bccbe0a36da51776bf4afd1b4a0d4348ff4/src/Core/Services/GraphQLSchemaCreator.cs#L213-L216)

That operation neglects to check whether a "read" operation is defined for the entity. When a read operation is not defined for an entity, but another action is defined for the entity such as 'create', the generated ObjectTypeDefinition has zero fields added that map to the entity. 
- e.g. entity 'book' will have GraphQL object type definition created without fields like id, title, publisher_id. 

Consequently, the generated input filters `ProductOrderByInput` and `ProductFilterInput` (for entity ProductCatalogue) will have no fields defined and will result in a HotChocolate schema validation error.
https://github.com/Azure/data-api-builder/blob/dacf3bccbe0a36da51776bf4afd1b4a0d4348ff4/src/Service.GraphQLBuilder/Queries/InputTypeBuilder.cs#L39-L55

**Comment by seantleonard** [comment]
See analysis above for determining to close.
