### ISSUE TITLE
CLI binary lacks execute permissions

### ISSUE THREAD

**Issue by aaronpowell** [Azure/data-api-builder#1197]
I've just downloaded the `0.5.0` release and the `Microsoft.DataApiBuilder` binary for the CLI does not have executable permissions, meaning that until you run `chmod +x` on it, you can't run the CLI:

![file system attributes](https://user-images.githubusercontent.com/434140/217137206-e83eb828-963b-4870-bcbe-069da357b841.png)

This problem is particularly noticeable with the SWA integration, which downloads DAB in the background and then tries to launch it, only to fail:

```
[swa] ✔ Downloading https://dataapibuilder.azureedge.net/releases/download/v0.5.0-beta/dab_linux-x64-0.5.0.zip@0.5.0
[dataApi] /bin/sh: 1: /home/node/.swa/dab/0.5.0/Microsoft.DataApiBuilder: Permission denied
[dataApi] cd "/workspaces/dab-trivia-game/data" && "/home/node/.swa/dab/0.5.0/Microsoft.DataApiBuilder" start -c staticwebapp.database.config.json exited with code 126
--> Sending SIGTERM to other processes..
[run] cd "/workspaces/dab-trivia-game/app" && npm run dev exited with code SIGTERM
--> Sending SIGTERM to other processes..
[swa] node "/workspaces/dab-trivia-game/node_modules/@azure/static-web-apps-cli/dist/msha/server.js" exited with code SIGTERM
✖ SWA emulator stoped because SWA emulator exited with code SIGTERM.
```

**Comment by seantleonard** [comment]
Fixed in SWA via: https://github.com/Azure/static-web-apps-cli/pull/662
https://github.com/Azure/static-web-apps-cli/blame/dc37b72f98ca6cb6f9cbcb5b0ecadf66a9dbe869/src/core/dataApiBuilder/dab.ts#L77


![Image](https://github.com/Azure/data-api-builder/assets/6414189/3825b037-ac7f-468d-86a8-1727d2485729)


Can be documented in DAB Docs to add execute bit.
