### ISSUE TITLE
[Bug]: Property names in REST json response should be camel-cased 

### ISSUE THREAD

**Issue by sebader** [Azure/data-api-builder#1419]
### What happened?

(I'n new to trying data-api-builder)

I've connected an Azure SQL DB and querying data via REST. This all works so far but I realized that the property names in the JSON response are exactly like my database table names and starting with upper case.

According to common JSON practices - as well as the [Microsoft REST API guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#710-response-formats) which are also linked in this repo - the property names should be camel-cased.

![image](https://user-images.githubusercontent.com/11445087/230306645-4d29fcb0-6b09-4689-9175-0d92b8bdbeb9.png)

So at a minimum I'd request a config switch so users can control this behavior.

### Version

Microsoft.DataApiBuilder 0.6.13+32fc03f4fe439d02aef454f10cc58e50d0d29f79

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI), Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aniruddh25** [comment]
Hi @sebader 
Does the `mappings` section of the configuration file documented here 
https://github.com/Azure/data-api-builder/blob/main/docs/configuration-file.md#mappings help with what you are looking for?

**Comment by sebader** [comment]
Well I could use that but I would then need to manually maintain that for every column. I'd much rather have a general setting for that.

**Comment by aaronburtle** [comment]
> Well I could use that but I would then need to manually maintain that for every column. I'd much rather have a general setting for that.

The issue here is that we don't have a way of really knowing the intent of the user and how their columns should be named prior to requests being made. We don't want to make assumptions about modifying the contents of their column names, and so we instead provide the ability to map those names to whatever they'd like.

As an silly, but illustrating example, imagine a column that is named "photoid", not representing "photo id", but representing a small random bit of information captured from a photo that is then stored in that column. Should photoids then automatically have their property name camel cased to "photoID"?

Providing a way to do this automatically may be a feature that we add in the future, but for now we will only offer the mapping as a way to modify the property names in the JSON of the columns returned.
