### ISSUE TITLE
[Question]: Listening Port

### ISSUE THREAD

**Issue by fgbustoa** [Azure/data-api-builder#1424]
Is it possible to set the listening TCP ports for service (instead of defaults 5000/5001) ?

They are hardcoded ?

**Comment by yorek** [comment]
While there are no specific configuration options in Data API builder at the moment, since it is a regular .NET Core application, you can use the `ASPNETCORE_URLS` variable to set the desired listening address and ports, as explained here:

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#url-prefixes-1

With PowerShell, for example, you can do something like:

```powershell
$env:ASPNETCORE_URLS="http://localhost:8080;https://localhost:8081"
```

if you are on Linux, instead:

```bash
export ASPNETCORE_URLS="http://localhost:8080;https://localhost:8081"
```

and the start Data API builder as usual via 

```shell
dab start
```

and it will be listening on port 8080 and 8081

**Comment by yorek** [comment]
While there are no specific configuration options in Data API builder at the moment, since it is a regular .NET Core application, you can use the `ASPNETCORE_URLS` variable to set the desired listening address and ports, as explained here:

https://learn.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0#url-prefixes-1

With powershell, for example, you can do something like:

```poweshell
$env:ASPNETCORE_URLS="http://localhost:8080;https://localhost:8081"
```

if you are on Linux, instead:

```bash
export ASPNETCORE_URLS="http://localhost:8080;https://localhost:8081"
```

and the start Data API builder as usual via 

```shell
dab start
```

and it will be listening on port 8080 and 8081

**Comment by yorek** [comment]
Thanks! Since this is a question that might be interesting to other users, I moved question and answer into the Discussions page, to make future discoverability easier: https://github.com/Azure/data-api-builder/discussions/1425. Closing this issue to avoid duplications, let's discuss more, if needed, there :)
