### ISSUE TITLE
[Bug]: Inconsistent Example Schema for Request Body of Stored-Procedure in Swagger UI

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#1509]
### What happened?

Example schema for request body shown for stored-procedure is not consistent.

To reproduce:
1. Use the dab-config.MsSql.json to start the engine.
2. open the swagger UI through the endpoint : https://localhost:5001/swagger

Inconsistencies noted:
1. Empty schema for request Body shown for **/InsertBook** (missing parameter info)
![image](https://github.com/Azure/data-api-builder/assets/102276754/a969d039-dc60-4686-ad4d-ce9b380644fb)

2. Incorrect request body schema shown for **/CountBook**,  (should be empty json, as it doesn’t need params)
![image](https://github.com/Azure/data-api-builder/assets/102276754/2a7287a6-4dc8-4b1e-a533-47ddeb039d88)
 
3. Incorrect request body schema shown for **/UpdateBookTitle**,  (publisher_id is not required in the request payload.)
![image](https://github.com/Azure/data-api-builder/assets/102276754/4ca60420-aa97-4118-89ac-3071cec5e3cd)
Similar issue with **/GetAuthorsHistoryByFirstName** and **/InsertAndDisplayAllBooksUnderGivenPublisher**

### Version

0.7.5

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
`/CountBook` SP incorrectly created by erroneously including the parameter `total_books` 
- This is because the DAB engine does not distinguish whether a SP parameter is required in `StoredProcedureDefinition`'s `ParameterDefinition`. Consequently, there is no way to know whether to mark parameters/parameter body of a stored procedure in the OpenAPI document, as required. 
  - To correctly mitigate, we need add a field to the sp `ParameterDefinition` identifying whether the value needs to be supplied in the request: Non-Nullable AND no default value. Also, separate logic to handle stored procedures is needed in the function `IsRequestBodyRequired()`, because function currently iterates through "columndefinitions" regardless of DatabaseObject/SourceDefinition type. which results in the erroneous SP result set column showing up as a parameter in the openapi doc.
  - Also add logic when creating the component schemas to create objects for SP request and response -> request object will consist of parameters, and response object will be columns.
  - Alternatively, if the current mitigation is to set the parameter in the runtime configuration with a default value so OpenAPI can document the parameter, then the Swagger doc can execute the request. The caveat is that the request executes with the default value when that may not be desired.

**Comment by seantleonard** [comment]
fix is in branch. Tests can be written against new config pr once merged.
