### ISSUE TITLE
[Bug]: GET call with parameters for stored-procedure is not working through Swagger

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#1510]
### What happened?

Making GET calls that requires parameters is not supported i believe. The requests are failing saying missing parameters but i do not see any option to enter the missing params.

To reproduce:

1. Use the dab-config.MsSql.json to start the engine.
2. open the swagger UI through the endpoint : https://localhost:5001/swagger

## Error: 
![image](https://github.com/Azure/data-api-builder/assets/102276754/6a6dec62-43c0-43fa-a317-550ab4774e30)

It is not showing text box to allow entry of the parameter id.
The generated url should look something like: 
https://localhost:5001/api/GetBook?id=1

Here is an example: [Swagger UI](https://petstore.swagger.io/#/pet/findPetsByStatus)

### Version

0.7.5

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Issue Looks to arise from:
- Stored procedure entity which does not list parameters in the runtime config. The parameter at fault in this issue is a required parameter, where the SP entity is set to be accessed via the GET HTTP verb, where a query parameter defines the sp parameter and value.
- To resolve: This is dependent on Data API builder implementing OpenAPI documentation of Query Parameters for GET endpoints, which is on the backlog. Once implemented, the GET request Parameters section in the OpenAPI description doc will have a value. 

-Tests: need to validate that required query parameters / stored procedure parameters are documented, even when not specified in the runtime configuration (because they are not required to be specified? - To be verified)

```tsql
USE [dabdev]
GO
/****** Object:  StoredProcedure [dbo].[get_book_by_id]    Script Date: 6/9/2023 4:42:46 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[get_book_by_id] @id int AS
      SELECT * FROM dbo.books
      WHERE id = @id
```

Stored procedure has parameter `id` of type int.

The entity runtime config definition:
```json
    "GetBook": {
      "source": {
        "type": "stored-procedure",
        "object": "get_book_by_id"
      },
      "permissions": [
        {
          "role": "anonymous",
          "actions": [
            "execute"
          ]
        },
        {
          "role": "authenticated",
          "actions": [
            "execute"
          ]
        }
      ],
      "rest": {
        "path": true,
        "methods": [
          "get"
        ]
      },
      "graphql": false
    }
```

A Postman request with successful execution on GET endpoint: 
```http
GET http://localhost:5000/api/GetBook?id=1
```

**Comment by abhishekkumams** [comment]
#1572 contains details on implemeting the query parameters. closing this.
