### ISSUE TITLE
Cleanup sample config files for REST on entities to NOT support Boolean path

### ISSUE THREAD

**Issue by aaronpowell** [Azure/data-api-builder#1547]
In #1402 support was added for the REST config of an entity to be:

```json
"MyEntity": {
  "rest": {
    "path": true
  }
}
```

This wasn't previously supported so the schema file needs to be updated to support it.

## Context

Reopening as I encountered that my local config, and config files present in the test project have `"path": true` used, which results in an engine startup failure.

Schema file is accurate to only support 'string' as you two mention: https://github.com/Azure/data-api-builder/blob/90229412a221cb0caaefd450fca57debd4bc9bf9/schemas/dab.draft.schema.json#L286C15-L288

I'll submit a PR to fix the files in the test project (so we don't increase file count here). 

I confirming whether the CLI tool properly adheres to the schema requirement so we don't have to tag this as a breaking change.

_Originally posted by @seantleonard in https://github.com/Azure/data-api-builder/pull/1402#discussion_r1238990524_

**Comment by seantleonard** [comment]
Closing this as current behavior of "main" is to require a string for the path. Error message is helpful:
> The value of path must be a string. Found True."
![image](https://github.com/Azure/data-api-builder/assets/6414189/dd34394a-ead6-4d47-a501-3f9d7b4e4a88)

Additionally, 0.5.35 behavior disallows the usage of `true` or `false` and requires a string. The error is not really helpful because the location of the error is obfuscating behind line numbers.:
> System.Text.Json.JsonException: The JSON value could not be converted to System.String. Path: $ | LineNumber: 0 | BytePositionInLine: 4.
![image](https://github.com/Azure/data-api-builder/assets/6414189/10a06cb7-04c1-4e35-963f-9807118a461e)
