### ISSUE TITLE
Need to unignore test once behavior of stored procedures is fixed

### ISSUE THREAD

**Issue by ayush3797** [Azure/data-api-builder#1570]
### What happened?

Currently, we are ignoring this test: https://github.com/Azure/data-api-builder/blob/ca3c4448106d67bb2bca7370f38c0c30857c2095/src/Service.Tests/Unittests/ConfigValidationUnitTests.cs#L1858 because the behavior of rest.methods property is not functioning correctly. The methods property is only relevant for stored-procedures but it is also getting populated for tables/views. Will have to un-ignore the test once behavior is fixed.

**Comment by ayush3797** [comment]
FYI @severussundar @Aniruddh25.

**Comment by severussundar** [comment]
For tables and views, the CLI writes out all the 5 HTTP verbs in `Methods` field. 

This particular test tries to populate the methods field with just `GET` for a table (possibly to simulate the scenario of editing the config by hand?).  Even if the config is hand-edited to have only `GET`, all the 5 HTTP actions are successfully enabled which is the right behavior as per design.

The test expects an error to be thrown when deserializing a config which has `Methods` array populated for tables/views - which needs to thought through again. IMO, the current behavior - irrespective of the value present in the `Methods` field in the config file, enabling of all 5 HTTP actions is in-line with the design decision.

**Comment by severussundar** [comment]
At the moment, when an entity backed by a table or view is created, CLI writes out all the 5 REST methods in the config file. Since, the `methods` property does not play any role for tables and views (When tables/views are exposed for REST, all 5 HTTP actions are enabled by design. Only for stored-procedures, there is option of configuring a set of HTTP verbs that can be enabled), it need not be written out to the config file for tables and views. [This issue](https://github.com/Azure/data-api-builder/issues/1571) tracks the effort for the same. 

At the moment, If the config file is hand-edited to add the methods property manually, it is not honored and all the 5 HTTP actions are supported (as noted in my previous comment).  

Currently, presence of extra fields does not lead to errors.
For example, For stored procedures, adding `key-fields` in the `source` section does not lead to errors during deserialization and validation. At the same time, the addition of `key-fields` does not play any role/have any effect since it is applicable only for views. Same is the case with adding `parameters` in the `source` section for tables/views. Doesn't lead to errors, at the same time has no effect as it relevant only for stroed procedures. 

A similar approach could be followed here
1. CLI will not write out the `methods` field for tables and views to the config file. 
2. CLI does not provide a way to declare `methods` for tables and views - this validation already exists.
3. Addition of `methods` field manually to the config file does not lead to error and has no effect - all the 5 HTTP methods will be enabled if the entity is exposed via REST endpoints.
