### ISSUE TITLE
[Enhancement] Startup.cs Runtimeconfigloader is tied to the filesystem implementation.

### ISSUE THREAD

**Issue by rohkhann** [Azure/data-api-builder#1593]
When runtimeconfigloader logic was moved to a base class to enable different implementations, we tightly couples startup.cs logic with the filesystem loader implementation. This task is to improve that logic and not have such a tight coupling for future scenarios where different runtimeconfigloaders could be used to load a runtime config.

**Comment by aaronpowell** [comment]
We'll need to think through how this is handled as there are a series of interconnected dependencies for the way the `RuntimeConfig` is used as part of the startup process of the service.

I was thinking through it today and here's the key points. First, we new up the `FileSystemRuntimeConfigLoader` here:

https://github.com/Azure/data-api-builder/blob/f260f2889508af501b8ae7ce7f83db57c3491276/src/Service/Startup.cs#L61-L66

Realistically this should be done in the DI container rather than us using the constructor, but we can't do that because we need the instance of the `RuntimeConfigProvider` (created [here](https://github.com/Azure/data-api-builder/blob/f260f2889508af501b8ae7ce7f83db57c3491276/src/Service/Startup.cs#L67)).

The reason for this is that we call the `ConfigureAuthentication` method:

https://github.com/Azure/data-api-builder/blob/f260f2889508af501b8ae7ce7f83db57c3491276/src/Service/Startup.cs#L474-L540

This method requires the `RuntimeConfigProvider` to be passed to it so that it can get the `RuntimeConfig` and decide on what kind of authentication we need to configure for the runtime.

We'll have to consider just how this refactor is going to work, and whether there is a way we can "delay" the registration of the auth pipeline until after the DI container is built, so that we can register all the appropriate types (Loader and Provider) and then resolve them, rather than creating them ourselves. @seantleonard might have some thoughts on how this could be possible.

**Comment by Aniruddh25** [comment]
This has been completed by #1587
