### ISSUE TITLE
RFC: Enable Application Insights

### ISSUE THREAD

**Issue by Aniruddh25** [Azure/data-api-builder#1601]
https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core?tabs=netcorenew%2Cnetcore6
```[tasklist]
### Tasks
- [ ] https://github.com/Azure/data-api-builder/issues/1704
- [ ] https://github.com/Azure/data-api-builder/pull/1649
```

**Comment by JerryNixon** [comment]
I suggest the following structure in the configuration file to store the AI instrumentation key.

````JSON
{
 "$schema": "https://github.com/Azure/data-api-builder/releases/download/v0.6.13/dab.draft.schema.json",
 "data-source": { ... },
  "runtime": { ... },
  "graphql": { ... },
  "host": { ... },
  "telemetry": {
    "application-insights": {
      "enabled": true,
      "instrumentation-key": "{YOUR_INSTRUMENTATION_KEY}"
    }
  }
}
````

This supports the current goal of Application Insights without precluding it as the only supported service.

Example of other:

````JSON
{
 "$schema": "https://github.com/Azure/data-api-builder/releases/download/v0.6.13/dab.draft.schema.json",
 "data-source": { ... },
  "runtime": { ... },
  "graphql": { ... },
  "host": { ... },
  "telemetry": {
    "other-telemetry": {
      "enabled": true,
      "api-key": "{OTHER_TELEMETRY_API_KEY}"
    }
  }
}
````

Thoughts? @Aniruddh25 @abhishekkumams

**Comment by Aniruddh25** [comment]
@JerryNixon,
The properties `host`/`graphql` are under the parent `runtime` section that is globally applicable to the complete configuration file. Did you intend to put the `telemetry` section as the child of `runtime` so that it can be a sibling to `host`/`graphql` OR is it intended to be a sibling of `runtime`?

What should be the behavior:
- When this property is not specified in the config file?
- If `enabled` is not specified, but only api-key is specified?
- If enabled is specified and true, but api-key is missing? Should we error or give a warning?
- Can more than 1 telemetry objects be added? Should it be an array in that case? Can customer configure multiple application insights instances?
- When we do dab init, should the telemetry section be automatically added or not?

**Comment by JerryNixon** [comment]
Some thoughts, I look forward to your feedback:

1. When this property is not specified in the config file?

Since without a key, remote telemetry cannot be published to any endpoint, it makes sense that the DAB behavior should be that the entire capability is similar to `enabled: false`. 

2. If enabled is not specified, but only api-key is specified?

Since with a key, remote telemetry can be published, `enabled` seems optional, mainly present so that telemetry can be disabled without removing the entire section from the configuration (say, during development). 

3. If enabled is specified and true, but api-key is missing? Should we error or give a warning?

Since without a key, remote telemetry can be published, if `enabled: true` we can interpret this as a configuration mismatch and raise an error to the developer to indicate that `enabled: true` is incompatible with a missing key. 

4. Can more than 1 telemetry objects be added? Should it be an array in that case? Can customer configure multiple application insights instances?

I am not sure. I think we can push this decision until we support more than Application Insights. It is difficult to dream up a scenario where you would want to publish to two or more telemetry endpoints. But... maybe?

5. When we do dab init, should the telemetry section be automatically added or not?

No. Telemetry will be an add-on to DAB where, for example, in the CLU you would do something along the lines `dab add-telemetry:key,true` or something like that we can discuss a little later. 

These are all good questions, let me ask some more:

6. If telemetry fails in any way, should we somehow raise this error in the application? I think, no. 
7. Can the telemetry key be read from `env(key-name)`? I think, yes.
8. If two sections are marked as true, what do we do? I think, ignore this for now.
9. Should we instrument every endpoint? I think, yes. 
10. Should endpoint instrumentation include the URL? I am not sure.  Probably not. 
11. Should endpoint instrumentation include the request payload? I am not sure. Probably not. 
12. Should endpoint instrumentation include the response payload? I am not sure. Probably not. 
13. Should endpoint instrumentation aggregate result counts and log them? Almost certainly, yes.

There is prob. more to consider, but not sure if any of it is critical or a blocker.

**Comment by abhishekkumams** [comment]
[support for instrumentation key ingestion will end](https://learn.microsoft.com/en-us/azure/azure-monitor/app/asp-net-core?tabs=netcorenew%2Cnetcore6)

So, using connection-string is encouraged.

```json
{
  "runtime": {
    "telemetry": {
      "application-insights": {
        "enabled": true,
        "connection-string": "{APP_INSIGHTS_CONNECTION_STRING}"
      }
  }
}
```

**Connection string can be easily obtained from Azure Portal by navigating to Overview tab on Applicaiton Insights resource page.**

**Comment by abhishekkumams** [comment]
for the second question
```
If enabled is not specified, but only api-key is specified?
Since with a key, remote telemetry can be published, enabled seems optional and defaulted to true, mainly present so that telemetry can be disabled without removing the entire section from the configuration (say, during development).
```

I feel defaulting the enabled property to true may not be the best idea if the user may not want to publish the logs every time. By defaulting the enabled property to false, we're giving the user more control over the behavior of the logging system and avoiding unnecessary data collection.
