### ISSUE TITLE
[Enhancement] Boolean values in CLI

### ISSUE THREAD

**Issue by JerryNixon** [Azure/data-api-builder#1679]
# Summary
Adjust CLI boolean switches to clearly allow both `true` and `false`.

> Note: this should be implemented soon to prevent future code churn. 

# Motivation
The example `-rest.disabled` is unclear as it seems like it should require the value `true` or `false` like `dab init -rest.disabled true`; however, the behavior is actually like this: its presence alone is the value `true` & the value `false` is only possible when the switch is not present. This is quite unintuitive and prone to error for developers who are not meticulously referencing our documentation. This original approach was loosely based on alignment with the AZ CLI but proves far too unintuitive to leave like it is. See below. 

# Old behavior
`dab init -rest.disabled` As stated above, the presence of the switch is a `true` value for the "negative" switch. The `false` value of this "negative switch, is to omit it from the CLI op. 

# New behavior
`dab init -rest.enabled false` As stated above, the positive switch receives either a `true` or `false` value to indicate the operation. It has defaults, but its omission is not necessary to set a specific value. It can set either `true` or `false` explicitly or fall back to the default in omission. In the case of some CLI switches, there may not be a default value, making its presence required.

## Important notes:

1. The original "negative" switch remains unchanged but is _deprecated_. The reason for this is **only** for backwards compatibility with the old behavior as we move forward. All "negative" switches will also be removed from any documentation & samples to discourage use going forward. We can discuss breaking changes before GA for "negative" switches. 
2. The new "positive" switch is not boolean, but a `true/false` enum. The reason for this is to overcome any limitations in the args library we are using. It will appear to be a boolean to the developer. As a result, the enum will simulate boolean behavior of passing `true` and `false`. 
3. Going forward, all boolean-like switches in the CLI will use this approach - both avoiding any "negative" switches and simulating boolean ops with a `true/false` enum.

**Comment by ayush3797** [comment]
Makes sense to me! A question: Since negative switches are deprecated but in a weird scenario (which may still occur) when a user uses both the flags in the init command, there can be a conflict: 
`dab init  ..... --rest.disabled --rest.enabled true`

I think we should:

1. Log a warning whenever the negative flag is included in the init command - that this is a deprecated feature and we recommend to use `rest.enabled` instead.
2. Log a warning that precedence will be given to the rest.enabled flag if included in the init command.

Same goes for other boolean flags.

**Comment by JerryNixon** [comment]
> 2. When there is a conflict between the two flags, throw an exception.

I completely agree. Throw an exception and remind them it is deprecated in the message.

**Comment by seantleonard** [comment]
@abhishekkumams I like the examples you provided. However, it doesn't look like we follow such a convention in DAB CLI for boolean **switches**. [dab cli doc](https://learn.microsoft.com/en-us/azure/data-api-builder/data-api-builder-cli). This may just be a documentation arrangement issue. For example, the docs say usage of `--set-session-context` in `dab init --set-session-context` has a default value of false. This is confusing because it makes me (and others as mentioned in parent issue description) think that you can provide a value with that switch or that including the switch means setting session context is disabled (false).

@JerryNixon This issue should also be specific about flags (`-`) versus switches(`--`) (and consider what CommandLineParser package allows us to do @abhishekkumams). 

i.e. 
- [Switch --] `--enable-rest-endpoint` versus the negative `--disable-rest-endpoint` with no values is pretty self-explanatory and doesn't leave room for confusion/double-negatives like: `--disable-rest-endpoint false`
- [Flag -] `-rest-endpoint true` versus the negative `-rest-endpoint false`

I'm tailoring my examples after having read through an arbitrary example https://superuser.com/a/1181719 which describes

> According to [Build Awesome Command-Line Applications in Ruby 2][2] the main distinction is: a `switch` doesn't take arguments, while a `flag` does. Quoting directly from the book (page 15):
> 
> [![enter image description here][1]][1]
> 
> Typically, if a switch is in the long-form (for example `--foo`), which turns “on” some behavior, there is also another switch preceded with `no-` (for example `--no-foo`) that turns “off” the behavior.
> 
> Finally, long-form flags take their argument via an equal sign, whereas in the short form of a flag, an equal sign is typically not used. For example, the `curl` command, which makes HTTP requests, provides both short-form and long-form flags to specify an HTTP request method: `-X` and `--request`, respectively. The following example invocations show how to properly pass arguments to those flags:
> 
>     curl -X POST http://www.google.com
>     curl --request=POST http://www.google.com
> 
> 
>   [1]: https://i.stack.imgur.com/dYX60.png
>   [2]: https://www.amazon.com/dp/1934356913
>

**Comment by abhishekkumams** [comment]
@seantleonard , we can update our docs to be more clear about the usage of boolean flags
