### ISSUE TITLE
[Bug]: Multidatabase configuration does not recognize the endpoint

### ISSUE THREAD

**Issue by kliszaq** [Azure/data-api-builder#1761]
### What happened?

With the configuration for the multidatabase support, the endpoint from the auxiliary configuration file is not recognized and the exception is thrown (method GetEntityNameAndPrimaryKeyRouteFromRoute of the Rest service line https://github.com/Azure/data-api-builder/blob/3176820ac95fe973ad51bca5cdc1599c7b4dc088/src/Core/Services/RestService.cs#L459).

There is an invalid assumption that we have to consider only the default data source to recognize the paths and assigned entities.

There are 2 places that naively implement this approach: RestService.GetEntityNameAndPrimaryKeyRouteFromRoute and SqlQueryEngine.ExecuteAsync (https://github.com/Azure/data-api-builder/blob/3176820ac95fe973ad51bca5cdc1599c7b4dc088/src/Core/Resolvers/SqlQueryEngine.cs#L138). The assumption is that via GetDefaultDataSourceName() we find the ISqlMetadataProvider. 

The case I am reffering to, is that we have 2 configs: first one (global) is not exposing the endpoints, however the second one has one or more endpoints. When trying to hit it from the rest request, then always the enpoint is assumed to be tied to the global configuration file which is not true.

Proposed solution: to find the ISqlMetadataProvider by the enity/endpoint name instead of the default data source name.

### Version

0.8.52 3176820 for #1790

### What database are you using?

Azure SQL

### What hosting model are you using?

Static Web Apps (SWA)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
Hi @kliszaq, thank you for your suggestions!

While merged into main for evaluation, multiple database support is not yet a feature in any released version of DAB (`0.9.5-rc`, `0.8.52`/`SWA`) nor are multiple database sources supported on REST. Since REST only supports one data source, all entities are expected to be present in the provided runtime config file.

Let's continue the discussion in:
-  The multiple data source RFC #1638 to further discuss an empty `entities` property in the root config file.
-  The parent issue tracking REST support for multiple data sources: #1753 , to for ensuring `RestService` does not make the assumption of a default data source when multi data source support is designed/implemented.

Closing this issue so that we can consolidate into the two issues mentioned above.

**Comment by Aniruddh25** [comment]
Closing as "duplicate"
