### ISSUE TITLE
Support for OpenAPI description in a Infragistics AppBuilder integration use case

### ISSUE THREAD

**Issue by chrohrbach** [Azure/data-api-builder#2212]
### What happened?

It seems that DAB does not generate enough information when an endpoint is called by Infragistics AppBuilder that requires some details to be able to use the endpoint correctly, see the description [here](https://www.appbuilder.dev/help/using-data-in-your-app#openapi-swagger-endpoints-are-grayed-out). I searched for possibilities to configure the expressivness of DABs openapi interface but did not find any information about such a possibility. In a Infragistics forum post, see [here](https://www.infragistics.com/community/forums/f/indigo-design/125080/appbuilder-when-adding-rest-api-the-endpoints-are-disabled-and-not-selectable/549126#549126), the problem is described and solved with access to the underlying endpoint source code, i don't feel confident to go to the source code of DAB to check this. Thanks for your time in helping me out with this topic.

### Version

latest

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Which API approach are you accessing DAB through?

REST

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by chrohrbach** [comment]
It has been determined that Infragistics AppBuilder is looking for a missing property in the schema, see below
![image](https://github.com/Azure/data-api-builder/assets/2187381/4b0b73ad-037b-4978-8e10-979fa17236c5)
It is unclear if this is required by the OpenAPI specs or if it is a miss interpretation by Infragistics.

**Comment by pmoleri** [comment]
Here's the code that creates the Schema with `"properties"` but no `"type"`.
https://github.com/Azure/data-api-builder/blob/466c18a9c2eb9ccc808020319749f7681b13cfed/src/Core/Services/OpenAPI/OpenApiDocumentor.cs#L938-L941

**Comment by pmoleri** [comment]
I think this needs to be considered as a bug.
The lack of the "type" permits any other type as valid:
![image](https://github.com/Azure/data-api-builder/assets/12942794/1e844746-e87e-491b-a436-c61abe8b6bd4)

The mere presence of "properties" is not enough to specify type object.

**Comment by chrohrbach** [comment]
Thanks make sense. How do we go forward from here ?

**Comment by seantleonard** [comment]
Thank you for reporting, @chrohrbach. I'm working on a fix.

I found a relevant thread that discusses whether `type` is a required property. Consensus is that `type` isn't required:
- https://github.com/OAI/OpenAPI-Specification/issues/1657
  -  OpenAPI-Specification discussion
- https://github.com/PaloAltoNetworks/docusaurus-openapi-docs/issues/430
  - Example of how different tooling handles `type` or missing `type` differently.

Ultimately, different tooling handles the presence of the `type` property differently. Some may try to guess the type when not present:
- e.g. `object` when the property `properties` exists.

That said, there is no reason why DAB shouldn't add this so that Infragistics tooling can work. I'm curious whether this is the only error that Infragistics emits when evaluating the OpenAPI document generated by DAB.

**Comment by chrohrbach** [comment]
Thx for you work

**Comment by pmoleri** [comment]
Hi @seantleonard ,

Thank you for picking up this. While it's true that `type` is not required, I think it's incorrect in the context of DAB response.

 - `type` + `properties` means "**it must be an object** and the properties are as described
 - `properties` only means "it can be **any type**, when it's an object the properties are as described
   (see my validation example with a plain integer in the previous post).

DAB response is always an object and it's best described as such as it will improve compatibility.
I'm glad you agreed, I just wanted to provide additional input for the decision.
Thanks again

**Comment by seantleonard** [comment]
> Hi @seantleonard ,
> 
> Thank you for picking up this. While it's true that `type` is not required, I think it's incorrect in the context of DAB response.
> 
> * `type` + `properties` means "**it must be an object** and the properties are as described
> * `properties` only means "it can be **any type**, when it's an object the properties are as described
>   (see my validation example with a plain integer in the previous post).
> 
> DAB response is always an object and it's best described as such as it will improve compatibility. I'm glad you agreed, I just wanted to provide additional input for the decision. Thanks again

Sorry to imply that I was trying to justify whether to do this or not. I fully intend to do so.

I intended to figure out whether `type` was required because I wanted to identify why https://github.com/microsoft/OpenAPI.NET didn't complain about missing `type`. An error if `type` were required would have helped prevent this becoming an issue in the first place. Thanks for bringing this to my attention.

**Comment by JerryNixon** [comment]
Related #2262
