### ISSUE TITLE
[Bug]: Hot Reload Not Re-enabled When Switching from Production to Development Mode

### ISSUE THREAD

**Issue by abhishekkumams** [Azure/data-api-builder#2457]
### What happened?

When updating the environment mode from development to production, hot reload is disabled, which is expected behavior. However, when the environment is subsequently changed back from production to development, hot reload is not re-enabled. This behavior is not expected; ideally, if the initial mode was development, hot reload should automatically reactivate when the mode is reverted to development.

**Steps to Reproduce:**

1. Start the application in development mode with hot reload active.
2. Change the environment mode to production.
3. Change the environment mode back to development.

**Expected Behavior:**
Hot reload should be re-enabled automatically when the environment is set back to development mode.

**Actual Behavior:**
Hot reload remains inactive after switching from production to development mode.

### Version

1.3.13-rc

### What database are you using?

Azure SQL

### What hosting model are you using?

Local (including CLI)

### Relevant log output

```Text

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by seantleonard** [comment]
While yes we did consider "Production" -> "Development" mode as part of the scope, this change becomes difficult because there are checks in DAB that evaluate "IsHotReloadEnabled()" which considers dev/prod mode and forbids hot reload when in prod mode. You'd need to signal to hot reload functions that the "Mode" is explicitly changing.

If building in support for this, I'd recommend ensuring that the change includes logging that indicates hot reload is occurring because of a dev/prod mode switch.

Also would be beneficial to check dev mode to prod mode hot reload scenario. There are some instances in startup that are conditioned on Dev mode/prod mode only and those may be skipped when switching mode via hot reload as startup has already completed.

**Comment by abhishekkumams** [comment]
I gave more thoughts on this and believe its best to keep the existing functionality:

1. Maintain the current behavior where hot reload does not automatically resume when switching back to development mode.
2. This forces a conscious decision to re-enable hot reload and reduces risks associated with inadvertent switches or malicious toggles.

**Comment by aaronburtle** [comment]
We can close this issue then we if want to keep the current functionality. If we decide to change back in the future, because the ability to hot-reload would be gated behind starting the engine in dev mode, it should be safe to simply use the built in functions we have for determining of it is safe to hot-reload or not, or what mode we are in. This is because if the engine was started on prod mode, these will never be called in a hot-reload scenario, due to that functionality being unavailable. However, it would be important to clarify to users that we do not intend for starting in dev mode, then switching to production mode and using DAB in production this way.

I have a branch with the changes needed if we want this in the future to change. Very simple change.

![Image](https://github.com/user-attachments/assets/31872d83-7ad8-4f98-89a6-a8e4c2dbc181)

**Comment by aaronburtle** [comment]
Some updates after we had a discussion in a sync up. The current functionality really doesn't make sense. If you start DAB in development mode, then you switch to production mode, you risk having things that are setup for dev mode infiltrating your production scenario.

So, if we want to prevent that from happening, the solution is not to prevent hot-reload out of production mode, it is to prevent the hot-reloading of mode altogether.

This means the two options that make the most sense would either be the original intended logic, whereby whatever mode you start dab in is the scenario you are within, and if you start in development mode we let you arbitrarily swap back and forth between modes to speed up your development cycle and see how the changes youve made effect DAB when youre in production mode. Or, it would be to close down the DAB engine if any hot-reload of the mode from development to production was attempted. This deviates from the normal validation errors we would see, whereby we go back to a last known good config, because this config would be semantically correct, just with an attempt at changing mode. In that case, to avoid drift between the in-memory config and a valid config file, we should simply kill DAB.

**Comment by abhishekkumams** [comment]
> Some updates after we had a discussion in a sync up. The current functionality really doesn't make sense. If you start DAB in development mode, then you switch to production mode, you risk having things that are setup for dev mode infiltrating your production scenario.
> 
> So, if we want to prevent that from happening, the solution is not to prevent hot-reload out of production mode, it is to prevent the hot-reloading of mode altogether.
> 
> This means the two options that make the most sense would be:
> 
> 1. The originally intended logic, where if you start dab in dev mode we consider this a development scenario and allow you to freely hot-reload the mode so that you can quickly test how changes you are making will impact things in production mode. With this option the infiltration of dev mode specific properties of dab into the production mode makes sense because you are in a development scenario simply testing how things will work in production mode.
> 2. Do not allow for hot-reloading the mode at all, and instead close down the DAB engine if any hot-reload of the mode from development to production was attempted. This prevents any possibility from having features intended for development scenarios to infiltrate into production mode, and if a developer wants to test how the changes theyve been making while in dev mode work in production mode they would have to restart the engine in production mode.

I would support the second option considering the below factors:
1. Prevents development-specific configurations from impacting production, avoiding potential critical issues.
2. Restarting the DAB engine ensures a fresh, isolated state for each environment, reducing errors.
3. Supporting hot-reload between modes adds extra complexity to the logic, that may not be needed.

**Comment by aaronburtle** [comment]
Behavior that we decided on.

**Mode** will be ignored for the purposes of hot-reload. Any other changes that are valid for the given mode you are in will happen, but any changed to mode will be ignored. Currently, this means that if the engine is started in production, then all hot-reload is ignored. Eventually, when log-level hot-reload is supported for production, then any changes other than log-level will be ignored in production. And if started in dev mode, any changes to mode will be ignored.

We will print to console those changes that are ignored so that the user is aware of drift between their current config file and what the engine is using on-memory.
