### ISSUE TITLE
[Bug]: varbinary(MAX) parsed wrong

### ISSUE THREAD

**Issue by JefSeys** [Azure/data-api-builder#2472]
### What happened?

I have a column varbinary(MAX) that is being parsed as a string in Data API Builder. When this value is returned, the result is different as the value in SQL.
DAB openapi:
![Image](https://github.com/user-attachments/assets/5dec5e84-f2b6-4e21-86df-ad91d2b78dc3)
![Image](https://github.com/user-attachments/assets/9bb929bf-8c26-4d6e-b7f5-e5292599b1ce)
SQL:
![Image](https://github.com/user-attachments/assets/624de046-33c0-4a78-998c-610bd2f19193)
![Image](https://github.com/user-attachments/assets/9d260313-4c13-401a-8568-397bbdacfa78)

### Version

1.2.14

### What database are you using?

Azure SQL

### What hosting model are you using?

Container Apps

### Which API approach are you accessing DAB through?

REST

### Relevant log output

```Text

```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by abhishekkumams** [comment]
Thanks @JefSeys, for reporting the bug. I'm able to repro it.

**Comment by JefSeys** [comment]
Thank you!
Will it be fixed in a next release? Do you have an estimation?

**Comment by JerryNixon** [comment]
At least for now, our plan is not to "fix" this because we do not see how to implement an intuitive change that ensures the integrity of the Response payload.

## Why Base64 in the First Place?

As you know, JSON is a text-based data format designed for transmitting structured data efficiently. It inherently does not support binary data directly. Encoding binary data (e.g., images, files) into JSON requires converting it to a text-compatible format like Base64.

## Some Typical Pros of Base64

1. Base64 ensures binary data compatibility within JSON.
2. Base64 is widely supported across languages, making it easy to convert.

## Some Honest Cons of Base64

1. Base64 can increase binary data up to 33%, which sucks for very large files.
2. While converting Base64 is straightforward, it adds computational overhead.

## Workaround Example

In most cases, this process can be made transparent enough that the conversion is a non-issue.

```csharp
public class User
{
    public int Id { get; set; }
    public string Name { get; set; }
    public string Photo { get; set; }

    [JsonIgnore]
    public byte[] PhotoBinary => Convert.FromBase64String(Photo);
}
```

## Conclusion

At this time, we will not be "fixing" this issue because, not only is it intentional, it is the best solution given the many constraints, the various systems, and the diverse customer base using Data API Builder. That said, I am open to exploring alternate approaches we could consider if you have suggestions. This is pretty common, though. However, I hope it is clear that this is not a bug in the sense of a flaw in the code—it is an intentional decision due to type incompatibilities.
