### ISSUE TITLE
[Known Issue] Mutations not correctly created for many-to-many relationship

### ISSUE THREAD

**Issue by yorek** [Azure/data-api-builder#479]
Not sure if this is a bug or by design, but it seems that mutations do not reflect that many-to-many relationships. For example in a Book-Authors, when I use `createBook` to create a book I cannot specify the list of authors Id that should be associated with the book.

**Comment by Falven** [comment]
Is this still a limitation? Is there some sort of comprehensive log of DB operation limitations?

**Comment by aaronpowell** [comment]
I've been thinking about what could be a good approach here and my thought is that we should automatically generate the mutations required for editing relationships based off the relationship information present in the `dab-config.json`.

Let's take these entities and their relationship from the sample SQL database:

```json
    "Author": {
      "source": "dbo.authors",
      "permissions": [
        {
          "role": "anonymous",
          "actions": ["*"]
        }
      ],
      "relationships": {
        "books": {
          "cardinality": "many",
          "target.entity": "Book",
          "linking.object": "dbo.books_authors"
        }
      }
    },
    "Book": {
      "source": "dbo.books",
      "permissions": [
        {
          "role": "anonymous",
          "actions": ["*"]
        }
      ],
      "relationships": {
        "authors": {
          "cardinality": "many",
          "target.entity": "Author",
          "linking.object": "dbo.books_authors"
        }
      }
    }
```

Presently, we have to map the `book_authors` table as an entity in the config (or use a stored procedure), but we already know the singular/plural of each entity (`Book` and `Author`), as well as the database table to insert/delete from (`dbo.books_authors` via `linking.object`), so why don't we automatically generate an entity named `BookAuthor` and then we can do the GraphQL mutations from that, basically we'd generate this:

```json
    "BookAuthor": {
      "source": "dbo.books_authors",
      "permissions": [
        {
          "role": "anonymous",
          "actions": ["*"]
        }
      ]
    }
```

For you, which in turn would generate `createBookAuthor`, `updateBookAuthor` and `deleteBookAuthor`.

If we wanted to take it a step further, we could generate a more specific "relationship" entity in the internal object structure and only generate the `create` and `delete` mutation (since `update` doesn't make _that much_ sense). Or rather than creating singular create/delete, we could have it generate bulk ones, such as:

```graphql
mutation Mutations {
  createBookAuthors(bookId: Int! authorIds: [Int!]!): Book!
  deleteBookAuthors(bookId: Int! authorIds: [Int!]!): Book!
  createAuthorBooks(authorId: Int! bookIds: [Int!]!): Author!
  deleteAuthorBooks(authorId: Int! bookIds: [Int!]!): Author!
}
```

These would be specific mutations representing the relationship direction (starting with `Book` or `Author`) and allowing a list of IDs to add as the relationship.

This can become more complex when the mapping table expands beyond two columns, but I'm not sure how common that is.

**Comment by seantleonard** [comment]
@ayush3797 @severussundar can this item be tracked with nested mutations, if required?

**Comment by severussundar** [comment]
Hey @seantleonard, through the nested inserts feature, they would be able to accomplish what is described in the description ---> Create a book + associate it with a list of authors; both in a single operation.

I've linked this issue to the parent issue for nested mutations. This is added as a related item in the parent issue.

**Comment by severussundar** [comment]
Through multiple create feature, this use-case is enabled now
